---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: remove-a-vm-win-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: remove_vm
  extra_vars: {
"vm_name": "vm-win-rhdh"
}

